# Basic
title: 指甲的博客
subtitle: 发现、记录、整理、分享
# welcome_message: <a href="https://github.com/ZhijiaTian/ZhijiaTian.github.io" target="_blank">Download the theme</a>
description: Welcome to ZHIJIA BLOG.
creator: <a href="http://zhijiadeboke.xyz">@指甲</a>

url: "http://zhijiadeboke.xyz"

permalink: /:categories/:title

# Format
highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
nav:
    - {title: 新浪微博,  in_site: false,  description: 指甲的新浪微博,    url: 'https://weibo.com/tianzhejia'}
    - {title: CSDN,     in_site: false,  description: 指甲的CSDN,        url: 'https://blog.csdn.net/qq_35605018'}
    - {title: GitHub,   in_site: false,  description: 指甲的GitHub,      url: 'https://github.com/ZhijiaTian'}
    - {title: 目录,      in_site: true,   description: 博客目录,         url: '/timeline'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

gems:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-redirect-from

# Pagination
# plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: 指甲
    # duoshuo: 
    
# Social
social:
    # weibo: zhijia
    # github: ZhijiaTian
    # CSDN: 指甲的博客
    # gplus: 107108267983477358170
    rss: /feed.xml
    mail: 2461824656@qq.com
    copyright: http://choosealicense.online

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
