# Basic
title: 指甲的博客
subtitle: 发现、记录、整理、分享
# welcome_message: <a href="https://github.com/ZhijiaTian/ZhijiaTian.github.io" target="_blank">Download the theme</a>
description: Welcome to ZHIJIA BLOG.
creator: <a href="http://onev.cat">@指甲</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Support Me, description: Support Me, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: zhijia
    github: ZhijiaTian
    CSDN: 指甲的博客
    gplus: 107108267983477358170
    mail: 2461824656@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
